spring:
  config:
    import: optional:configserver:http://localhost:8888
  spring:
    flyway:
      baseline-on-migrate: true
      validate-on-migrate: true
  application:
    name: product-service
logging:
  level:
    org.flywaydb: DEBUG